user_name = (input("import your name:"))
profile = (input("import your profile:"))
number_phone = (input("import your phone number:"))
favourite_story = (input("import your favourite story:"))
time = (input("What's time now:"))
day = (input("What day:"))
math = (input("Can you ask the answer of your question in your calculation in math in your think:"))
calculation = (input("import your caculation:"))
question = (input("Ask question:"))
if question == "How are you": print("I'm good")
if question == "How old are you": print("I'm 20")
if question == "What's your name": print("My name is siri")
if question == "Am I handsome": print("Yes, you are")
if question == "Am I beautiful": print("Yes, you are")
if question == "Where are you": print("I'm here")
if question == "Where do you live": print("I live in ")
if question == "Who's the president in united state": print("Joe Biden is the president of United State")
if question == "Can I get your number phone": print("No, you can't is security")
if question == "What's your father name": print("My father name is Bach")
if question == "What's your favourite colour": print("My favourite colour is my father favourite colour")
if question == "Hey Siri": print("Yes,", user_name)
if question == "Can you tell my profile": print("", profile)
if question == "Can you tell my number phone": print("", number_phone)
if question == "Are you know my favourite story": print("Yes, I know is", favourite_story)
if question == "Who are you": print("I'm Siri and i'm your virtual assistant")
if question == "What's time now": print("time now is", time)
if question == "What's day": print("Today is", day)
if question == "Who am i": print("You're", user_name)
if question == calculation: print("the answer is", math)



